### ISSUE TITLE
etcd watch cannot get correct history

### ISSUE THREAD

**Issue by danielzheng** [coreos/etcd#3168]
Hi,

I am using etcd of v2.1.1 now, but actually this problem is in all version of etcd.
Here are the steps how to reproduce this issue:
I have a cluster with 3 node(node1, node2, node3).
At the very beginning, it works very well.
1. Using etcdctl to set "/key" to value "aaa", all the nodes could get the update.
2. shutdown node2 and node3,
3. run "etcdctl" command to set "/key" to "bbb"
4. run "etcdctl" command to set "/key" to "ccc"
5. start node2 and node3, then all nodes sync "/key" value to "ccc"
6. watch key "/key" to get change history on this key, always got "aaa" and got returned index less then waitIndex.

I thought it's a big problem for anybody who need to continuous watch key changes.

Thanks.
Daniel

**Comment by yichengq** [comment]
Could you list the command that you used and the output in details?

**Comment by xiang90** [comment]
@yichengq Have you tried to reproduce the issue?

**Comment by yichengq** [comment]
@xiang90 I tried but failed.

@danielzheng Here are some hints that might be helpful:
1. In step 3 and 4, etcdctl should tell you that it fails to set the value. It indicates that it have no guarantee whether "/key" value is updated.
2. In some cases, the key could update to ccc. And I could watch the whole history that it changes from aaa to ccc.
3. For watch, the returned event index is always bigger than waitIndex.

**Comment by danielzheng** [comment]
@yichengq 
I am using the lastest release 2.1 to reproduce this issue this morning.
More details as below:
From step 3:
Operations on node1 which still works, set /aaa value 1, 2, 3 successively.
[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# curl -v -X PUT http://127.0.0.1:2379/v2/keys/aaa -d value=1            
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> PUT /v2/keys/aaa HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> Content-Length: 7
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 7 out of 7 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< X-Etcd-Cluster-Id: e7e8c4eca3670486
< Date: Fri, 31 Jul 2015 02:12:44 GMT
< Content-Length: 35
< 
* Connection #0 to host 127.0.0.1 left intact
{"message":"Internal Server Error"}[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# curl -v -X PUT http://127.0.0.1:2379/v2/keys/aaa -d value=2
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> PUT /v2/keys/aaa HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> Content-Length: 7
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 7 out of 7 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< X-Etcd-Cluster-Id: e7e8c4eca3670486
< Date: Fri, 31 Jul 2015 02:13:17 GMT
< Content-Length: 35
< 
* Connection #0 to host 127.0.0.1 left intact
{"message":"Internal Server Error"}[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# curl -v -X PUT http://127.0.0.1:2379/v2/keys/aaa -d value=3
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> PUT /v2/keys/aaa HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> Content-Length: 7
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 7 out of 7 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< X-Etcd-Cluster-Id: e7e8c4eca3670486
< Date: Fri, 31 Jul 2015 02:13:53 GMT
< Content-Length: 35
< 
* Connection #0 to host 127.0.0.1 left intact
{"message":"Internal Server Error"}[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# 

Then start up node2 and node3, get value of /aaa
[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# curl -v -X GET http://127.0.0.1:2379/v2/keys/aaa    
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> GET /v2/keys/aaa HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: e7e8c4eca3670486
< X-Etcd-Index: 213243
< X-Raft-Index: 4214951
< X-Raft-Term: 37842
< Date: Fri, 31 Jul 2015 02:16:17 GMT
< Content-Length: 96
< 
{"action":"get","node":{"key":"/aaa","value":"3","modifiedIndex":213241,"createdIndex":213241}}
* Connection #0 to host 127.0.0.1 left intact

Here just remember the latest modifiedIndex of /aaa is 213241.

Now get history of /aaa by watch and some weird things happened:
[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# curl -v -X GET "http://127.0.0.1:2379/v2/keys/aaa?wait=true&waitIndex=213180"
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> GET /v2/keys/aaa?wait=true&waitIndex=213180 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: e7e8c4eca3670486
< X-Etcd-Index: 213243
< X-Raft-Index: 4216047
< X-Raft-Term: 37842
< Date: Fri, 31 Jul 2015 02:25:25 GMT
< Transfer-Encoding: chunked
< 
{"action":"set","node":{"key":"/aaa","value":"bbb","modifiedIndex":213172,"createdIndex":213172},"prevNode":{"key":"/aaa","value":"fff","modifiedIndex":115666,"createdIndex":115666}}
* Connection #0 to host 127.0.0.1 left intact

returned modifiedIndex 213172 is less than watch index 213180.

And 

When I set the watch index as the latest modifiedIndex 213241:
[root@CentOS7_1 etcd-v2.1.1-linux-amd64]# curl -v -X GET "http://127.0.0.1:2379/v2/keys/aaa?wait=true&waitIndex=213241"   
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> GET /v2/keys/aaa?wait=true&waitIndex=213241 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: e7e8c4eca3670486
< X-Etcd-Index: 213243
< X-Raft-Index: 4215907
< X-Raft-Term: 37842
< Date: Fri, 31 Jul 2015 02:24:15 GMT
< Transfer-Encoding: chunked
< 
{"action":"set","node":{"key":"/aaa","value":"bbb","modifiedIndex":213172,"createdIndex":213172},"prevNode":{"key":"/aaa","value":"fff","modifiedIndex":115666,"createdIndex":115666}}
* Connection #0 to host 127.0.0.1 left intact

Incorrect histroy.

But from wal of node2 or node3, I can see the value 1, 2, 3 have been synced from node1 by using etcd-dump-logs:
37842      4214507      norm    method=SYNC time="2015-07-31 10:12:37.897660339 +0800 CST"
37842      4214508      norm    method=PUT path="/1/aaa" val="1"
37842      4214509      norm    method=SYNC time="2015-07-31 10:12:38.397735594 +0800 CST"
...
37842      4214575      norm    method=SYNC time="2015-07-31 10:13:11.397725685 +0800 CST"
37842      4214576      norm    method=PUT path="/1/aaa" val="2"
37842      4214577      norm    method=SYNC time="2015-07-31 10:13:11.897315491 +0800 CST"
...
37842      4214648      norm    method=SYNC time="2015-07-31 10:13:47.398162005 +0800 CST"
37842      4214649      norm    method=PUT path="/1/aaa" val="3"
37842      4214650      norm    method=SYNC time="2015-07-31 10:13:47.897435198 +0800 CST"

Hope these info could help you.

Thanks a lot.

Daniel Zheng

**Comment by yichengq** [comment]
Does the wait on node1 work well?

I definitely want to dig it more. Could you send all your data dirs to me (yicheng.qin@coreos.com)?

**Comment by danielzheng** [comment]
@yichengq wait have the same behavior on every single node.
I can reproduce this bug very easy. 
I was gonna send you a email with data dirs but the data size is pretty huge (228M).

**Comment by yichengq** [comment]
@danielzheng It is rather important for us to get the data dir, so we could locate what the problem is. Could you help to upload the data to dropbox or 网盘? And my QQ number is 263100761.

What is the traffic characteristics to etcd? What is the first version of etcd that uses this data dir? I hope that can help me to reproduce it better.

**Comment by danielzheng** [comment]
@yichengq I have sent you an e-mail about the URL of data-dir tarball and passwd. Hopefully, this could help you to find the root cause of this issue.
Thanks.

**Comment by yichengq** [comment]
@danielzheng I think your data dir is directly migrated from etcd 0.4 data dir, right? old etcd has some bug on this, and we have fixed it today. Instead of data dir migration, could you use [snapshot migration](https://github.com/coreos/etcd/blob/release-2.1/Documentation/backward_compatibility.md#snapshot-migration)? It should work well.

**Comment by yichengq** [comment]
@danielzheng This should be a problem in etcd 0.4 data dir and data-dir migration, so etcd 2.x cannot parse the store correctly. Have you ever seen/reproduced this under etcd 2.x?

If you still want to upgrade from etcd 0.4 to 2.x, I recommend snapshot migration.

**Comment by yichengq** [comment]
What I have done so far:
1. I tried to reproduce the bug from a fresh data-dir, but I failed. I could always get correct watch result from any member.
2. I checked the data directory of yours. The data in event history, which is used for watch, is wrong and may have gap. Moreover, the log entries in WALs(the first one is 0000000000000000-0000000000000000.wal) start from a big index, and contains only several tens of etcd key operations. These operations are recorded correctly in event history. So I think your data directory is upgraded from 0.4, and it may have some bugs in the data-dir migration process.

**Comment by yichengq** [comment]
@danielzheng ping

**Comment by danielzheng** [comment]
@yichengq Sorry for the late response.

I have tested what you said. That's right, this issue has been addressed in the latest version of etcd if I startup a fresh cluster from scratch.
This issue is not only exist in 0.4. I remember that in some non-release 2.x version, I can still reproduce this problem.

Thanks a lot.

**Comment by xiang90** [comment]
@danielzheng Thanks for the reply. Sorry for the problem etcd 0.4 caused you.
