### ISSUE TITLE
hack/tls-setup tools is broken

### ISSUE THREAD

**Issue by agalitsyn** [coreos/etcd#5837]
### Env
```
$ ./bin/etcd --version
etcd Version: 3.0.0+git
Git SHA: 581f847
Go Version: go1.5.4
Go OS/Arch: linux/amd64
```

### Steps to reproduce

```
$ go get github.com/coreos/etcd
$ cd $GOPATH/src/github.com/coreos/etcd
$ ./build
$ cd hack/tls-setup
$ make
$ goreman start
```

### Actual result
```
10:58:57 etcd3 | 2016-07-01 10:58:57.845691 N | membership: set the initial cluster version to 3.0
10:58:57 etcd2 | 2016-07-01 10:58:57.849779 N | membership: set the initial cluster version to 3.0
10:58:57 etcd1 | 2016-07-01 10:58:57.850985 N | membership: set the initial cluster version to 3.0
10:58:57 etcd3 | 2016-07-01 10:58:57.954489 I | api: enabled capabilities for version 3.0.0
10:58:57 etcd3 | 2016-07-01 10:58:57.954847 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
10:58:58 etcd1 | 2016-07-01 10:58:58.031714 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
10:58:58 etcd2 | 2016-07-01 10:58:58.066854 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
10:58:58 etcd3 | 2016-07-01 10:58:58.073724 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
```

### Expected results

Tool works as it was on revision 374b14e

**Comment by xiang90** [comment]
@agalitsyn What are the client commands that you sent to etcd server?

**Comment by gyuho** [comment]
@xiang90 I can reproduce in linux machine. Just `goreman start` will return these errors...

**Comment by xiang90** [comment]
@gyuho OK. We should fix it then.

**Comment by gyuho** [comment]
Sure, I will investigate more to fix it.

**Comment by agalitsyn** [comment]
@xiang90 right, I did just `goreman start` and nothing more.

**Comment by agalitsyn** [comment]
Can it be related with that etcd v3 uses gRPC, which use HTTP2, which means go1.6? I build etcd on go1.5.4. At least you might want mention this in doc.

**Comment by gyuho** [comment]
I built etcd master branch with Go tip, and still see this. We have TLS e2e tests, so it looks like some TLS configuration issue. We will investigate more.

Thanks for reporting!

**Comment by xiang90** [comment]
@agalitsyn I would suspect it is an internal issue (seem like the grpc gateway was complaining). We will take a look tomorrow morning. it is late night here at US.

**Comment by gyuho** [comment]
@agalitsyn I tried go1.6.2 and go1.7beta1 and works well (go tip as of yesterday doesn't work though...).

Can you try again with go1.6.2 or go1.7beta1? 

Thanks!

**Comment by xiang90** [comment]
http2 probably does not work well on go 1.5. so closing.

**Comment by agalitsyn** [comment]
@xiang90 works with go 1.6.2, here actions log for you

```
$ cd $GOPATH/src/github.com/coreos/etcd
$ docker run -it -v $(pwd):/go/src/github.com/coreos/etcd golang:1.6.2-alpine sh
# apk update
# apk add git make gcc musl-dev
# cd /go/src/github.com/coreos/etcd
# ./build
# ./bin/etcd --version
etcd Version: 3.0.0+git
Git SHA: 9405583
Go Version: go1.6.2
Go OS/Arch: linux/amd64
# cd hack/tls-setup
# make
# goreman start
```
result - no errors
