### ISSUE TITLE
functional-tester: fails with slow network injection

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#6891]
```
2016-11-22 03:14:04.210461 I | etcd-tester: [round#103 case#10] injected failure
2016-11-22 03:14:04.210497 I | etcd-tester: [round#103 case#10] recovering failure "slow down all members' network"
2016-11-22 03:14:16.638326 E | etcd-tester: keyStresser 10.240.0.2:2379 exited with error (rpc error: code = 2 desc = etcdserver: request timed out, possibly due to connection lost)
2016-11-22 03:14:16.638384 E | etcd-tester: keyStresser 10.240.0.2:2379 exited with error (rpc error: code = 2 desc = etcdserver: request timed out, possibly due to connection lost)
...
2016-11-22 03:18:07.869655 W | etcd-tester: #37 setHealthKey error (etcdserver: request timed out (http://10.240.0.2:2379))
...
2016-11-22 03:20:19.912039 W | etcd-tester: #59 setHealthKey error (context deadline exceeded (http://10.240.0.2:2379))
2016-11-22 03:20:20.912305 W | etcd-tester: [round#103 case#10] functional-tester returning with error (recovery error: context deadline exceeded (http://10.240.0.2:2379))
```

**Comment by gyuho** [comment]
@fanminshi Now we know `SIGQUIT` was from `cleanUp`, and it is expected.

Here's what happened:

Tester fails to talk to `10.240.0.2:2379`

```
2016-11-23 20:35:20.417097 I | etcd-tester: [round#41 case#2] recovering failure "slow down all members' network"
2016-11-23 20:35:35.420305 E | etcd-tester: keyStresser 10.240.0.2:2379 exited with error (rpc error: code = 2 desc = etcdserver: request timed out, possibly due to connection lost)
...
2016-11-23 20:35:38.419265 E | etcd-tester: keyStresser 10.240.0.2:2379 exited with error (rpc error: code = 2 desc = etcdserver: request timed out, possibly due to connection lost)
2016-11-23 20:35:42.060742 W | etcd-tester: #0 setHealthKey error (context deadline exceeded (http://10.240.0.2:2379))
2016-11-23 20:35:48.061607 W | etcd-tester: #1 setHealthKey error (context deadline exceeded (http://10.240.0.2:2379))
```

`10.240.0.2:2379` shows:

```
2016-11-23 20:35:19.705346 W | etcdserver: timed out waiting for read index response
2016-11-23 20:35:20.385543 W | etcdserver: ignored out-of-date read index response (want [236 240 88 146 82 188 102 134], got [236 240 88 146 82 188 102 168])
2016-11-23 20:35:21.385769 W | etcdserver: timed out waiting for read index response
2016-11-23 20:35:21.738151 W | etcdserver: ignored out-of-date read index response (want [236 240 88 146 82 188 102 168], got [236 240 88 146 82 188 102 223])
2016-11-23 20:35:26.058181 I | raft: 609030006db2ecf0 is starting a new election at term 49
2016-11-23 20:35:26.058238 I | raft: 609030006db2ecf0 became candidate at term 50
...
2016-11-23 20:35:34.260823 I | raft: 609030006db2ecf0 became follower at term 56
2016-11-23 20:35:34.260834 I | raft: 609030006db2ecf0 [logterm: 49, index: 22528355, vote: 0] cast MsgVote for 2cb9a50a6fb4fb53 [logterm: 49, index: 22535078] at term 56
2016-11-23 20:35:34.262257 I | raft: raft.node: 609030006db2ecf0 elected leader 2cb9a50a6fb4fb53 at term 56

# tester sent SIGQUIT
2016-11-23 20:41:37.380474 N | pkg/osutil: received quit signal, shutting down...

2016-11-23 20:41:37.380524 I | etcdserver: skipped leadership transfer for stopping non-leader member
2016-11-23 20:41:37.380619 I | rafthttp: stopping peer 2cb9a50a6fb4fb53...
...
2016-11-23 20:41:37.383565 I | rafthttp: stopped peer 462e0a42b3aef1f7

SIGQUIT: quit
PC=0x75322f m=0
```



`10.240.0.2:2379` agent log also shows that it had sent `SIGQUIT`:

```
2016-11-23 20:34:59.269993 I | etcd-agent: set latency of 500ms (+/- 50ms)
2016-11-23 20:35:01.115099 I | etcd-agent: removing latency
2016-11-23 20:35:18.661296 I | etcd-agent: set latency of 500ms (+/- 50ms)
2016-11-23 20:35:20.385817 I | etcd-agent: removing latency
2016-11-23 20:41:37.380196 I | etcd-agent: cleanup etcd
2016-11-23 20:41:37.380244 I | etcd-agent: [DEBUG] sending signal "quit"
```

So `SIGQUIT` part all works as expected. We just need to figure out why etcd server was not able to process client requests.

`10.240.0.2:2379` log `2016-11-23 20:35:34.262257 I | raft: raft.node: 609030006db2ecf0 elected leader 2cb9a50a6fb4fb53 at term 56` shows that `10.240.0.2:2379` has no problem with communicating with the leader since there was no leader election since then. But somehow client requests kept failing in this node.

**Comment by gyuho** [comment]
Still investigating... for reference

<br>

##### Updates 10:30AM, Nov 29, 2016

Turns out [`processInternalRaftRequestOnce`](https://github.com/coreos/etcd/blob/master/etcdserver/v3_server.go#L693) was timing out (5s).

I added more logs as below

```go
func (s *EtcdServer) processInternalRaftRequestOnce(ctx context.Context, r pb.InternalRaftRequest) (*applyResult, error) {

	...

	cctx, cancel := context.WithTimeout(ctx, s.Cfg.ReqTimeout())
	defer cancel()

	if r.Put != nil && string(r.Put.Key) == "health" {
		plog.Printf("[DEBUG] processInternalRaftRequest Propose PutRequest 1 with %+v", r.Put)
	}

	start := time.Now()
	s.r.Propose(cctx, data)
	proposalsPending.Inc()
	defer proposalsPending.Dec()

	if r.Put != nil && string(r.Put.Key) == "health" {
		plog.Printf("[DEBUG] processInternalRaftRequest Propose PutRequest 2 with %+v", r.Put)
	}

	select {
	case x := <-ch:
		return x.(*applyResult), nil
	case <-cctx.Done():
		proposalsFailed.Inc()
		s.w.Trigger(id, nil) // GC wait
		if r.Put != nil && string(r.Put.Key) == "health" {
			plog.Printf("[DEBUG] processInternalRaftRequest Propose PutRequest error with %+v (%v)", r.Put, cctx.Err())
		}
		return nil, s.parseProposeCtxErr(cctx.Err(), start)
	case <-s.done:
		return nil, ErrStopped
	}
}
```

And in apply.go

```go
func (a *applierV3backend) Put(txnID int64, p *pb.PutRequest) (*pb.PutResponse, error) {
	now := time.Now()
	if p != nil && string(p.Key) == "health" {
		plog.Printf("[DEBUG] (a *applierV3backend) Put starts")
	}
	defer func() {
		if p != nil && string(p.Key) == "health" {
			plog.Printf("[DEBUG] (a *applierV3backend) Put ends (took %v)", time.Since(now))
		}
	}()
```

And here's what happened

```
# GOOD
2016-11-29 15:52:17.380632 I | etcdserver: [DEBUG] processInternalRaftRequest Propose PutRequest 1 with key:"health" value:"good" 
2016-11-29 15:52:17.380644 I | etcdserver: [DEBUG] processInternalRaftRequest Propose PutRequest 2 with key:"health" value:"good" 
2016-11-29 15:52:17.388885 I | etcdserver: [DEBUG] (a *applierV3backend) Put starts
2016-11-29 15:52:17.388928 I | etcdserver: [DEBUG] (a *applierV3backend) Put ends (took 41.004µs)
```

```
# FAILURE
2016-11-29 15:52:47.779372 I | etcdserver: [DEBUG] processInternalRaftRequest Propose PutRequest 1 with key:"health" value:"good" 
2016-11-29 15:52:47.779402 I | etcdserver: [DEBUG] processInternalRaftRequest Propose PutRequest 2 with key:"health" value:"good" 
2016-11-29 15:52:52.767120 I | etcdserver: [DEBUG] processInternalRaftRequest Propose PutRequest error with key:"health" value:"good"  (context canceled)
```

So `Propose` went through, but somehow `step MsgProp` never returns.


This node was follower

```
2016-11-29 15:52:30.166283 I | raft: raft.node: 879241f38b4913f9 elected leader f5ec0371ba91859d at term 600
2016-11-29 15:52:31.610922 I | rafthttp: receiving database snapshot [index:111626871, from f5ec0371ba91859d] ...
```

**Comment by xiang90** [comment]
@gyuho 

Great progress!

So the leader never received the proposal? I thought you told me once that the leader actually received the proposal from follower, but then the follower failed to receive the ack. So that is wrong?

We should trace down to find out where exactly the proposal get blocked or dropped at the follower side.

**Comment by gyuho** [comment]
Yeah leader never received proposal. Think I did it wrong previously.
I will trace down further to double check. Thanks!

**Comment by gyuho** [comment]
@xiang90 

Raft layer in etcdserver was blocking at `r.readStateC <- rd.ReadStates[len(rd.ReadStates)-1]` case.
https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L147

Then etcdserver raft never `Advance`, and `msgs` in Raft was queueing forever.
There were over 50,000 messages that never got sent to `Ready` when the tester failed.
So `MsgProp` from follower never made it apply layer--write requests from clients fail.


Giving bigger buffer size for `r.readStateC` solves this issue.
I tried buffer size 10 for `readStateC` (current buffer size is 1) with:

```diff
diff --git a/etcdserver/raft.go b/etcdserver/raft.go
index 6d6afdb..899634a 100644
--- a/etcdserver/raft.go
+++ b/etcdserver/raft.go
@@ -165,11 +165,19 @@ func (r *raftNode) start(rh *raftReadyHandler) {
                                }
 
                                if len(rd.ReadStates) != 0 {
+                                       toPrint := false
+                                       if len(r.readStateC) > 1 {
+                                               plog.Infof("[DEBUG] select rd := <-r.Ready() %d messages (committed entries %d, snapshot data %d), BEFORE r.readStateC[%d %d]", len(rd.Messages), len(rd.CommittedEntries), len(rd.Snapshot.Data), len(r.readStateC), cap(r.readStateC))
+                                               toPrint = true
+                                       }
                                        select {
                                        case r.readStateC <- rd.ReadStates[len(rd.ReadStates)-1]:
                                        case <-r.stopped:
                                                return
                                        }
+                                       if toPrint {
+                                               plog.Infof("[DEBUG] select rd := <-r.Ready() %d messages (committed entries %d, snapshot data %d), AFTER r.readStateC[%d %d]", len(rd.Messages), len(rd.CommittedEntries), len(rd.Snapshot.Data), len(r.readStateC), cap(r.readStateC))
+                                       }
                                }

```

And logs

```
2016-12-05 17:25:52.792754 W | etcdserver: timed out waiting for read index response
2016-12-05 17:25:53.793022 W | etcdserver: timed out waiting for read index response
2016-12-05 17:25:56.013455 I | etcdserver: start to snapshot (applied: 72369481, lastsnap: 72357814)
2016-12-05 17:25:56.021397 I | etcdserver: saved snapshot at index 72369481
2016-12-05 17:25:56.021619 I | etcdserver: compacted raft log at 72364481
2016-12-05 17:25:57.008354 W | etcdserver: timed out waiting for read index response
2016-12-05 17:25:58.008600 W | etcdserver: timed out waiting for read index response
2016-12-05 17:26:01.795246 W | etcdserver: timed out waiting for read index response
2016-12-05 17:26:02.317377 I | etcdserver: [DEBUG] select rd := <-r.Ready() 11 messages, before r.readStateC[2 10]
2016-12-05 17:26:02.317421 I | etcdserver: [DEBUG] select rd := <-r.Ready() 11 messages, after r.readStateC[3 10]
2016-12-05 17:26:02.317504 I | etcdserver: [DEBUG] select rd := <-r.Ready() 4 messages, before r.readStateC[3 10]
2016-12-05 17:26:02.317532 I | etcdserver: [DEBUG] select rd := <-r.Ready() 4 messages, after r.readStateC[4 10]
2016-12-05 17:26:02.364557 I | etcdserver: [DEBUG] select rd := <-r.Ready() 13 messages, before r.readStateC[4 10]
2016-12-05 17:26:02.364596 I | etcdserver: [DEBUG] select rd := <-r.Ready() 13 messages, after r.readStateC[5 10]
2016-12-05 17:26:03.009205 W | etcdserver: ignored out-of-date read index response (want [76 99 88 205 233 185 192 159], got [76 99 88 205 233 185 192 249])
2016-12-05 17:26:03.009244 W | etcdserver: ignored out-of-date read index response (want [76 99 88 205 233 185 192 176], got [76 99 88 205 233 185 192 249])
2016-12-05 17:26:03.009252 W | etcdserver: ignored out-of-date read index response (want [76 99 88 205 233 185 192 178], got [76 99 88 205 233 185 192 249])
2016-12-05 17:26:03.009259 W | etcdserver: ignored out-of-date read index response (want [76 99 88 205 233 185 192 235], got [76 99 88 205 233 185 192 249])
2016-12-05 17:26:03.009266 W | etcdserver: ignored out-of-date read index response (want [76 99 88 205 233 185 192 237], got [76 99 88 205 233 185 192 249])
2016-12-05 17:26:04.009384 W | etcdserver: timed out waiting for read index response
```



I noticed the buffer in `r.readStateC` is filled up over 2, like every 10 minute (once `r.readStateC` is overloaded after processing snapshot from leader). For current workload, buffer size 10 would be big enough--no failure even after 1k runs.


Or is it safe to skip sending read states when `raft.Message` or `raft.CommittedEntries` in `raft.Ready` is empty?

```
2016-12-05 21:50:17.355519 W | etcdserver: timed out waiting for read index response
2016-12-05 21:50:18.357230 W | etcdserver: timed out waiting for read index response
2016-12-05 21:50:19.357565 W | etcdserver: timed out waiting for read index response
2016-12-05 21:50:19.914125 I | etcdserver: [DEBUG] select rd := <-r.Ready() 1 messages (committed entries 0, snapshot data 0), BEFORE r.readStateC[2 10]
2016-12-05 21:50:19.914176 I | etcdserver: [DEBUG] select rd := <-r.Ready() 1 messages (committed entries 0, snapshot data 0), AFTER r.readStateC[3 10]
2016-12-05 21:50:21.363277 W | etcdserver: ignored out-of-date read index response (want [77 54 88 208 211 54 92 3], got [77 54 88 208 211 54 92 20])
2016-12-05 21:50:21.363329 W | etcdserver: ignored out-of-date read index response (want [77 54 88 208 211 54 92 5], got [77 54 88 208 211 54 92 20])
2016-12-05 21:50:21.363340 W | etcdserver: ignored out-of-date read index response (want [77 54 88 208 211 54 92 18], got [77 54 88 208 211 54 92 20])
2016-12-05 21:50:22.363476 W | etcdserver: timed out waiting for read index response
2016-12-05 21:50:22.691867 I | etcdserver: start to snapshot (applied: 5210782, lastsnap: 5200674)
2016-12-05 21:50:22.702687 I | etcdserver: saved snapshot at index 5210782
```

**Comment by xiang90** [comment]
@gyuho 

It is a deadlock. 

The routine that consumes readstateC waits on raft.Node to step in ReadIndex call: https://github.com/coreos/etcd/blob/master/etcdserver/v3_server.go#L786

The raft.Node routine waits from the consumer routine to read out the readStateC before it can step the ReadIndex call.

We should fix this deadlock. Adding buffer size wont reliably and completely solve this, right?

**Comment by gyuho** [comment]
@xiang90 You are right. Buffer size doesn't fix the root cause. I will try to fix the deadlock. Thanks.

**Comment by xiang90** [comment]
@gyuho An easy fix is to add 

```
case <-time.After(internalTimeout):
```

at the sender side too.
