### ISSUE TITLE
clientv3.Get seems to leak memory when called in go routines

### ISSUE THREAD

**Issue by chrizke** [coreos/etcd#7360]
Originally, I tried to use etcd as a simple database for a golang web server. Therefore, I initialized a clientv3 object once and for each HTTP request this client executes Get (or Put etc.). 

But the memory usage of this web server increases tremendously by time (i.e. by HTTP requests).

Here is a small code example replicating this behavior without a web server.
It has a memory usage of about 850MB for 50,000 Get calls.
Reducing it to 10,000 calls yields about 150MB.

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/coreos/etcd/clientv3"
)

func get(cli *clientv3.Client) {

	_, getErr := cli.Get(context.Background(), "mykey")
	if getErr != nil {
		panic(getErr)
	}
}

func testGet(num int) {

	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"127.0.0.1:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		panic(err)
	}
	defer cli.Close()

	for i := 0; i < num; i++ {
		go get(cli)
	}

	time.Sleep(20 * time.Second)
	fmt.Println("Done.")

}

func main() {
	testGet(50000)

	for {
	}
}
```

OS: Mac OS 10.11
Go: 1.8
clientv3: 2533c2a50c4b6114ad6fd4c0000175fac3b6ee06

**Comment by xiang90** [comment]
Thanks for reporting! Seems like a client bug.

**Comment by heyitsanthony** [comment]
This may be related to go-grpc.

I fixed up the initial test  (leak) to use waitgroups and got rid of the `for{}` and made a version that was grpc only (leak2):
```go
package main

import (
        "context"
        "fmt"
        "time"
        "sync"

        pb "github.com/coreos/etcd/etcdserver/etcdserverpb"
        "google.golang.org/grpc"
)

func get(kvc pb.KVClient) {
        reqrange := &pb.RangeRequest{Key: []byte("mykey")}
        if _, err := kvc.Range(context.TODO(), reqrange, grpc.FailFast(false)); err != nil {
                panic(err)
        }
}

func testGet(num int) {
        conn, err := grpc.Dial("127.0.0.1:2379", grpc.WithInsecure())
        if err != nil {
                panic(err)
        }
        kvc := pb.NewKVClient(conn)
        if err != nil {
                panic(err)
        }
        defer conn.Close()

        var wg sync.WaitGroup
        wg.Add(num)
        for i := 0; i < num; i++ {
                go func() {
                        defer wg.Done()
                        get(kvc)
                }()
        }

        wg.Wait()
        fmt.Println("Done.")
}

func main() {
        testGet(50000)
        time.Sleep(60 * time.Minute)
}
```

and got:
```
anthony   8274 10.5  4.9 1533216 813944 pts/13 Sl+  14:54   0:10 ./leak
anthony   8613  9.7  2.9 1039240 478472 pts/14 Sl+  14:54   0:08 ./leak2
```
(813MB vs 478MB). Setting FailFast=true had no effect.

with GOGC=10:
```
anthony  14164 18.3  4.7 1301152 782612 pts/13 Sl+  14:59   0:25 ./leak
anthony  14176 13.5  3.0 870272 506792 pts/14  Sl+  14:59   0:18 ./leak2
```
(782MB vs 506MB)

One thing to note here is there's still stray CPU overhead even after all RPCs complete.

clientv3 is also using the grpc balancer, so that might account for the extra overhead as well.

**Comment by yudai** [comment]
Did some tests with pprof and a forced GC. It seems there is no real memory leak here. But resources are not recovered by GC somehow? Sharing my observation FYI.

```go
package main

import (
  "context"
  "fmt"
  "net/http"
  _ "net/http/pprof"
  //  "runtime"
  "sync"
  "time"

  "github.com/coreos/etcd/clientv3"
)

func get(cli *clientv3.Client) {
  _, getErr := cli.Get(context.Background(), "mykey")
  if getErr != nil {
    panic(getErr)
  }
}

func testGet(num int) {
  cli, err := clientv3.New(clientv3.Config{
    Endpoints:   []string{"127.0.0.1:2379"},
    DialTimeout: 5 * time.Second,
  })
  if err != nil {
    panic(err)
  }
  defer cli.Close()

  var wg sync.WaitGroup
  wg.Add(num)
  for i := 0; i < num; i++ {
    go func() {
      defer wg.Done()
      get(cli)
    }()
  }

  wg.Wait()

  fmt.Println("Done.")
}

func main() {
  go http.ListenAndServe(":6000", nil)

  testGet(50000)
  //  runtime.GC()

  time.Sleep(1000000 * time.Hour)
}
```

No goroutine leaks anyway.

```
curl -s http://127.0.0.1:6000/debug/pprof/goroutine?debug=1
goroutine profile: total 5
1 @ 0x42e13a 0x429257 0x428899 0x557db8 0x557e24 0x55ad95 0x57702e 0x575299 0x65eacf 0x65d818 0x65d500 0x65e20f 0x45a7a1
#       0x428898        net.runtime_pollWait+0x58                       /home/yudai/.gvm/gos/go1.8.3/src/runtime/netpoll.go:164
#       0x557db7        net.(*pollDesc).wait+0x37                       /home/yudai/.gvm/gos/go1.8.3/src/net/fd_poll_runtime.go:75
#       0x557e23        net.(*pollDesc).waitRead+0x33                   /home/yudai/.gvm/gos/go1.8.3/src/net/fd_poll_runtime.go:80
#       0x55ad94        net.(*netFD).accept+0x1e4                       /home/yudai/.gvm/gos/go1.8.3/src/net/fd_unix.go:430
#       0x57702d        net.(*TCPListener).accept+0x2d                  /home/yudai/.gvm/gos/go1.8.3/src/net/tcpsock_posix.go:136
#       0x575298        net.(*TCPListener).AcceptTCP+0x48               /home/yudai/.gvm/gos/go1.8.3/src/net/tcpsock.go:215
#       0x65eace        net/http.tcpKeepAliveListener.Accept+0x2e       /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:3044
#       0x65d817        net/http.(*Server).Serve+0x227                  /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:2643
#       0x65d4ff        net/http.(*Server).ListenAndServe+0xaf          /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:2585
#       0x65e20e        net/http.ListenAndServe+0x7e                    /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:2787

1 @ 0x42e13a 0x42e21e 0x449479 0x85d02c 0x42dcea 0x45a7a1
#       0x449478        time.Sleep+0xf8         /home/yudai/.gvm/gos/go1.8.3/src/runtime/time.go:59
#       0x85d02b        main.main+0x7b          /home/yudai/tmp/etcddev/src/github.com/coreos/leak.go:52
#       0x42dce9        runtime.main+0x209      /home/yudai/.gvm/gos/go1.8.3/src/runtime/proc.go:185

1 @ 0x45a7a1

1 @ 0x653880 0x45a7a1
#       0x653880        net/http.(*connReader).backgroundRead+0x0       /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:655

1 @ 0x70ea32 0x70e830 0x70aea5 0x712231 0x712543 0x65abb4 0x65bff0 0x65d3b2 0x659722 0x45a7a1
#       0x70ea31        runtime/pprof.writeRuntimeProfile+0xa1  /home/yudai/.gvm/gos/go1.8.3/src/runtime/pprof/pprof.go:632
#       0x70e82f        runtime/pprof.writeGoroutine+0x9f       /home/yudai/.gvm/gos/go1.8.3/src/runtime/pprof/pprof.go:594
#       0x70aea4        runtime/pprof.(*Profile).WriteTo+0x3b4  /home/yudai/.gvm/gos/go1.8.3/src/runtime/pprof/pprof.go:302
#       0x712230        net/http/pprof.handler.ServeHTTP+0x1d0  /home/yudai/.gvm/gos/go1.8.3/src/net/http/pprof/pprof.go:209
#       0x712542        net/http/pprof.Index+0x1e2              /home/yudai/.gvm/gos/go1.8.3/src/net/http/pprof/pprof.go:221
#       0x65abb3        net/http.HandlerFunc.ServeHTTP+0x43     /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:1942
#       0x65bfef        net/http.(*ServeMux).ServeHTTP+0x12f    /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:2238
#       0x65d3b1        net/http.serverHandler.ServeHTTP+0x91   /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:2568
#       0x659721        net/http.(*conn).serve+0x611            /home/yudai/.gvm/gos/go1.8.3/src/net/http/server.go:1825
```

### Without GC

532MB by `ps`.

```
ps aux | grep leak
yudai    21303 41.8  6.5 889692 531612 pts/58  Sl+  14:15   0:18 ./leak
```

99MB by pprof

```
go tool pprof http://localhost:6000/debug/pprof/heap
Fetching profile from http://localhost:6000/debug/pprof/heap
Saved profile in /home/yudai/pprof/pprof.leak.localhost:6000.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top 20
99MB of 99MB total (  100%)
Dropped 40 nodes (cum <= 0.49MB)
Showing top 20 nodes out of 49 (cum >= 57.43MB)
      flat  flat%   sum%        cum   cum%
   27.51MB 27.79% 27.79%    27.51MB 27.79%  runtime.malg
   16.51MB 16.67% 44.46%    16.51MB 16.67%  github.com/coreos/etcd/vendor/golang.org/x/net/trace.newTrace
   13.50MB 13.64% 58.10%    45.93MB 46.39%  github.com/coreos/etcd/vendor/google.golang.org/grpc.invoke
   11.50MB 11.62% 69.72%    40.55MB 40.96%  runtime.systemstack
       7MB  7.07% 76.79%        7MB  7.07%  github.com/coreos/etcd/clientv3.Op.toRangeRequest
    6.50MB  6.57% 83.36%     6.50MB  6.57%  runtime.acquireSudog
       4MB  4.04% 87.40%        4MB  4.04%  context.WithValue
       3MB  3.03% 90.43%    49.93MB 50.43%  github.com/coreos/etcd/clientv3.(*retryKVClient).Range
       3MB  3.03% 93.46%     7.50MB  7.58%  github.com/coreos/etcd/vendor/google.golang.org/grpc/transport.(*http2Client).NewStream
    1.54MB  1.56% 95.01%     1.54MB  1.56%  runtime.allgadd
       1MB  1.01% 96.02%    46.93MB 47.40%  github.com/coreos/etcd/etcdserver/etcdserverpb.(*kVClient).Range
    0.92MB  0.93% 96.95%     0.92MB  0.93%  runtime.hashGrow
    0.52MB  0.52% 97.47%     0.52MB  0.52%  github.com/coreos/etcd/vendor/google.golang.org/grpc/transport.newFramer
    0.50MB  0.51% 97.98%     0.50MB  0.51%  github.com/coreos/etcd/vendor/google.golang.org/grpc/transport.(*http2Client).newStream
    0.50MB  0.51% 98.48%    57.43MB 58.01%  github.com/coreos/etcd/clientv3.(*kv).do
    0.50MB  0.51% 98.99%        3MB  3.03%  github.com/coreos/etcd/vendor/google.golang.org/grpc.newContextWithRPCInfo
    0.50MB  0.51% 99.49%     0.50MB  0.51%  runtime.rawstringtmp
    0.50MB  0.51%   100%     0.50MB  0.51%  runtime.stringtoslicebyte
         0     0%   100%    46.93MB 47.40%  github.com/coreos/etcd/clientv3.(*Client).newAuthRetryWrapper.func1
         0     0%   100%    57.43MB 58.01%  github.com/coreos/etcd/clientv3.(*kv).Do
```

### With a Forced GC

520MB by `ps`

```
ps aux | grep leak
yudai    31285 27.2  6.3 947572 520000 pts/58  Sl+  14:17   0:18 ./leak
```

23MB by pprof. Around 70MB was recovered.

```
go tool pprof http://localhost:6000/debug/pprof/heap
Fetching profile from http://localhost:6000/debug/pprof/heap
Saved profile in /home/yudai/pprof/pprof.leak.localhost:6000.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top 20
23246kB of 23246kB total (  100%)
Dropped 56 nodes (cum <= 116.23kB)
Showing top 20 nodes out of 32 (cum >= 1454.28kB)
      flat  flat%   sum%        cum   cum%
20488.13kB 88.14% 88.14% 20488.13kB 88.14%  runtime.malg
  942.23kB  4.05% 92.19%   942.23kB  4.05%  runtime.hashGrow
  788.96kB  3.39% 95.58%   788.96kB  3.39%  runtime.allgadd
  514.63kB  2.21% 97.80%   514.63kB  2.21%  math/rand.NewSource
  512.05kB  2.20%   100%  1454.28kB  6.26%  runtime.mapassign
         0     0%   100%   514.63kB  2.21%  crypto/rsa.init
         0     0%   100%   514.63kB  2.21%  crypto/tls.init
         0     0%   100%   514.63kB  2.21%  crypto/x509.init
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*Client).newAuthRetryWrapper.func1
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*kv).Do
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*kv).Get
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*kv).do
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*retryKVClient).Range
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*retryKVClient).Range.func1
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/clientv3.(*retryWriteKVClient).Range
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/etcdserver/etcdserverpb.(*kVClient).Range
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/vendor/golang.org/x/net/trace.(*traceSet).Add
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/vendor/golang.org/x/net/trace.New
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/vendor/google.golang.org/grpc.Invoke
         0     0%   100%  1454.28kB  6.26%  github.com/coreos/etcd/vendor/google.golang.org/grpc.invoke
(pprof)
[default]
```

After the last GC finishes, the allocated memory is still not returned to the OS so `ps` simply shows large size. However, you can see resources are actually recovered by the GC by using pprof.

If you use `debug.FreeOSMemory()`, you can see `ps` returns 65MB:

```
ps aux | grep leak
yudai     6733  9.5  0.8 1018904 65604 pts/58  Sl+  14:28   0:18 ./leak
```

```go
package main

import (
  "context"
  "fmt"
  "net/http"
  _ "net/http/pprof"
  "runtime"
  "runtime/debug"
  "sync"
  "time"

  "github.com/coreos/etcd/clientv3"
)

func get(cli *clientv3.Client) {
  _, getErr := cli.Get(context.Background(), "mykey")
  if getErr != nil {
    panic(getErr)
  }
}

func testGet(num int) {
  cli, err := clientv3.New(clientv3.Config{
    Endpoints:   []string{"127.0.0.1:2379"},
    DialTimeout: 5 * time.Second,
  })
  if err != nil {
    panic(err)
  }
  defer cli.Close()

  var wg sync.WaitGroup
  wg.Add(num)
  for i := 0; i < num; i++ {
    go func() {
      defer wg.Done()
      get(cli)
    }()
  }

  wg.Wait()

  fmt.Println("Done.")
}

func main() {
  go http.ListenAndServe(":6000", nil)

  testGet(50000)
  runtime.GC()
  debug.FreeOSMemory()

  time.Sleep(1000000 * time.Hour)
}
```

I'm wondering why the default GC cycles doesn't free up resources created in `invoke()` by default.

**Comment by yudai** [comment]
## Without a Forced (written) GC + time

I found that just leaving the process for a while is required to collect unused resources.

With GCtrace, you can see `GC forced` (it's actually not forced by the code) after `Done.`. It seems the runtime triggers this type of GC every 120 secs and some resources  are collected by these "forced" GC.

```
GODEBUG=gctrace=1 ./leak
gc 1 @0.437s 33%: 0.048+301+0.39 ms clock, 0.39+1350/599/215+3.1 ms cpu, 85->85->72 MB, 86 MB goal, 8 P
gc 2 @0.757s 44%: 0.11+285+0.18 ms clock, 0.22+1219/569/345+0.36 ms cpu, 73->73->72 MB, 144 MB goal, 8 P
gc 3 @1.509s 31%: 1.0+358+0.17 ms clock, 8.1+226/715/1617+1.3 ms cpu, 106->107->92 MB, 145 MB goal, 8 P
gc 4 @4.056s 15%: 14+148+0.15 ms clock, 116+111/292/607+1.2 ms cpu, 158->159->49 MB, 184 MB goal, 8 P
Done.
GC forced
gc 5 @125.555s 0%: 8.9+18+0.092 ms clock, 71+0/27/40+0.74 ms cpu, 89->89->22 MB, 98 MB goal, 8 P
scvg0: inuse: 32, idle: 456, sys: 489, released: 0, consumed: 489 (MB)
GC forced
gc 6 @245.596s 0%: 0.025+11+0.068 ms clock, 0.20+0/15/38+0.54 ms cpu, 22->22->22 MB, 45 MB goal, 8 P
GC forced
scvg1: 103 MB released
scvg1: inuse: 32, idle: 456, sys: 489, released: 103, consumed: 385 (MB)
gc 7 @365.612s 0%: 0.027+20+0.054 ms clock, 0.21+0/34/28+0.43 ms cpu, 22->22->22 MB, 45 MB goal, 8 P
```

After you see `22->22->22`, pprof actually reports 22MB and it looks there is no leaks eventually.

```
go tool pprof http://localhost:6000/debug/pprof/heap
Fetching profile from http://localhost:6000/debug/pprof/heap
Saved profile in /home/yudai/pprof/pprof.leak.localhost:6000.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top 30
23243.35kB of 23243.35kB total (  100%)
Dropped 63 nodes (cum <= 116.22kB)
      flat  flat%   sum%        cum   cum%
19975.92kB 85.94% 85.94% 19975.92kB 85.94%  runtime.malg
 1024.03kB  4.41% 90.35%  1024.03kB  4.41%  vendor/golang_org/x/net/http2/hpack.addDecoderNode
  942.23kB  4.05% 94.40%   942.23kB  4.05%  runtime.hashGrow
  788.96kB  3.39% 97.80%   788.96kB  3.39%  runtime.allgadd
  512.20kB  2.20%   100%   512.20kB  2.20%  github.com/coreos/etcd/vendor/golang.org/x/net/trace.newTrace
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*Client).newAuthRetryWrapper.func1
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*kv).Do
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*kv).Get
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*kv).do
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*retryKVClient).Range
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*retryKVClient).Range.func1
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/clientv3.(*retryWriteKVClient).Range
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/etcdserver/etcdserverpb.(*kVClient).Range
         0     0%   100%   942.23kB  4.05%  github.com/coreos/etcd/vendor/golang.org/x/net/trace.(*traceSet).Add
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/vendor/golang.org/x/net/trace.New
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/vendor/google.golang.org/grpc.Invoke
         0     0%   100%  1454.44kB  6.26%  github.com/coreos/etcd/vendor/google.golang.org/grpc.invoke
         0     0%   100%  1454.44kB  6.26%  main.get
         0     0%   100%  1024.03kB  4.41%  main.init
         0     0%   100%  1454.44kB  6.26%  main.testGet.func1
         0     0%   100%  1024.03kB  4.41%  net/http.init
         0     0%   100%  2478.47kB 10.66%  runtime.goexit
         0     0%   100%  1024.03kB  4.41%  runtime.main
         0     0%   100%   942.23kB  4.05%  runtime.mapassign
         0     0%   100% 20764.88kB 89.34%  runtime.mstart
         0     0%   100% 20764.88kB 89.34%  runtime.newproc.func1
         0     0%   100% 20764.88kB 89.34%  runtime.newproc1
         0     0%   100% 20764.88kB 89.34%  runtime.systemstack
         0     0%   100%  1024.03kB  4.41%  vendor/golang_org/x/net/http2/hpack.init
         0     0%   100%  1024.03kB  4.41%  vendor/golang_org/x/net/http2/hpack.init.1
```

This could be a runtime issue? go1.9beta2 seems to have a little bit more efficient GC, but still you need to wait for 120 secs.

**Comment by yudai** [comment]
Actually I realized that this is not a runtime issue, because the runtime triggers a GC when the heap size has increased `GOGC%`  (=100% by default) from the last iteration, so if nothing is happening by sleeping, the runtime simply waits for a force GC for 120 secs.

The 120 secs come from here:

```go
// forcegcperiod is the maximum time in nanoseconds between garbage
// collections. If we go this long without a garbage collection, one
// is forced to run.
//
// This is a variable for testing purposes. It normally doesn't change.
var forcegcperiod int64 = 2 * 60 * 1e9
```

https://github.com/golang/go/blob/093adeef4004fd029de1a8fd138802607265dc73/src/runtime/proc.go#L3763-L3768

Go's concurrent GC doesn't look good at this type of workload, because resources are created at once in a small amount of time and nothing happens after the spike. GC doesn't have a chance to dispose resources created in the spike in this case.

However, the upper limit is not infinite. Even if you change the code like below, you don't get x10 memory usage (actual usage is ~150MB). So there is a chance that a GC happens, unused resources are collected properly.

```go
  for i := 0; i < 10; i++ {
    testGet(100000)
  }
```

I think this is not a bug.

**Comment by xiang90** [comment]
@yudai Good analysis. Thanks! I think we should close this issue. 

/cc @heyitsanthony

**Comment by heyitsanthony** [comment]
OK, let's close it. Thanks for looking into this @yudai
